CREATE DATABASE pizzaria
\c pizzaria

CREATE TABLE usuarios (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(100),
    email VARCHAR(100) UNIQUE NOT NULL,
    senha VARCHAR(50) NOT NULL,
    tipo VARCHAR(20) DEFAULT 'comum'
);

CREATE TABLE pizzas (
    ID SERIAL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL,
    ESTOQUE INTEGER DEFAULT 0
);

CREATE TABLE vendas (
    ID SERIAL PRIMARY KEY,
    USUARIO_ID INTEGER REFERENCES USUARIOS(ID),
    PIZZA_ID INTEGER REFERENCES PIZZAS(ID),
    QUANTIDADE INTEGER NOT NULL,
    DATA_VENDA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO USUARIOS (nome, EMAIL, SENHA, TIPO) VALUES
('Ademir Pizzaria', 'admin@pizzaria.com', '123', 'admin'),
('Seu Zé', 'funcionario@pizzaria.com', '123', 'comum');

INSERT INTO PIZZAS (NOME, PRECO, ESTOQUE) VALUES
('Margheritta', 66.50, 10),
('Pepperoni', 64.00, 15),
('Chocolate', 75.00, 12);

INSERT INTO VENDAS (USUARIO_ID, PIZZA_ID, QUANTIDADE) VALUES
(2, 1, 2),
(2, 3, 1);

UPDATE PIZZAS
SET ESTOQUE = ESTOQUE - ( 
    SELECT COALESCE(SUM(QUANTIDADE), 0)
    FROM VENDAS
    WHERE VENDAS.PIZZA_ID = PIZZAS.ID
);

